if(EXISTS "/home/arif/Research/highway-vqsort/blockwise_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/blockwise_test[1]_tests.cmake")
else()
  add_test(blockwise_test_NOT_BUILT blockwise_test_NOT_BUILT)
endif()
