if(EXISTS "/home/arif/Research/highway-vqsort/combine_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/combine_test[1]_tests.cmake")
else()
  add_test(combine_test_NOT_BUILT combine_test_NOT_BUILT)
endif()
