if(EXISTS "/home/arif/Research/highway-vqsort/compare_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/compare_test[1]_tests.cmake")
else()
  add_test(compare_test_NOT_BUILT compare_test_NOT_BUILT)
endif()
