if(EXISTS "/home/arif/Research/highway-vqsort/compress_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/compress_test[1]_tests.cmake")
else()
  add_test(compress_test_NOT_BUILT compress_test_NOT_BUILT)
endif()
