if(EXISTS "/home/arif/Research/highway-vqsort/copy_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/copy_test[1]_tests.cmake")
else()
  add_test(copy_test_NOT_BUILT copy_test_NOT_BUILT)
endif()
