if(EXISTS "/home/arif/Research/highway-vqsort/crypto_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/crypto_test[1]_tests.cmake")
else()
  add_test(crypto_test_NOT_BUILT crypto_test_NOT_BUILT)
endif()
