if(EXISTS "/home/arif/Research/highway-vqsort/demote_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/demote_test[1]_tests.cmake")
else()
  add_test(demote_test_NOT_BUILT demote_test_NOT_BUILT)
endif()
