if(EXISTS "/home/arif/Research/highway-vqsort/find_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/find_test[1]_tests.cmake")
else()
  add_test(find_test_NOT_BUILT find_test_NOT_BUILT)
endif()
