if(EXISTS "/home/arif/Research/highway-vqsort/float_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/float_test[1]_tests.cmake")
else()
  add_test(float_test_NOT_BUILT float_test_NOT_BUILT)
endif()
