if(EXISTS "/home/arif/Research/highway-vqsort/logical_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/logical_test[1]_tests.cmake")
else()
  add_test(logical_test_NOT_BUILT logical_test_NOT_BUILT)
endif()
