if(EXISTS "/home/arif/Research/highway-vqsort/mask_mem_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/mask_mem_test[1]_tests.cmake")
else()
  add_test(mask_mem_test_NOT_BUILT mask_mem_test_NOT_BUILT)
endif()
