if(EXISTS "/home/arif/Research/highway-vqsort/mul_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/mul_test[1]_tests.cmake")
else()
  add_test(mul_test_NOT_BUILT mul_test_NOT_BUILT)
endif()
