if(EXISTS "/home/arif/Research/highway-vqsort/reduction_test[1]_tests.cmake")
  include("/home/arif/Research/highway-vqsort/reduction_test[1]_tests.cmake")
else()
  add_test(reduction_test_NOT_BUILT reduction_test_NOT_BUILT)
endif()
